services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"


  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - django-sqlite:/app/data


volumes:
  django-sqlite: {}

